/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.estoque.telas.produto;

import com.estoque.excecoes.produtos.PrecoInvalidoException;
import com.estoque.excecoes.produtos.ProdutoNaoEncontradoException;
import com.estoque.excecoes.produtos.QuantidadeInvalidaException;
import com.estoque.objetos.Produto;
import com.estoque.telas.*;
import com.estoque.listas.*;
import static com.estoque.listas.LeitorDeListas.lerLista;
import static com.estoque.listas.LeitorDeListas.gravarLista;

import javax.swing.*;
import java.awt.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author julio
 */
public class EditarProduto extends javax.swing.JFrame {
    public Produto p;
    public Produtos produtos;
    
    /**
     * Creates new form EditarProduto
     */
    public EditarProduto(Produtos produtos) {
        this.produtos = lerLista(produtos);
        initComponents();

        // seta a visibilidade de vários itens da tela como false para que só apareçam em outro momento,
        // quando forem necessários
        jLabel3.setVisible(false);
        jTextFieldCodigoNovo.setVisible(false);
        jTextFieldNome.setVisible(false);
        jTextFieldPreco.setVisible(false);
        jTextFieldQuantidade.setVisible(false);
        jComboBoxTipoQuantidade.setVisible(false);
        jTextFieldDescricao.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPesquisar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonRetornarMenuProduto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jTextFieldCodigo = new com.estoque.telas.icons.JTextFieldHint(new JTextField(), "empty", "Código");
        ;
        jButtonEditar = new javax.swing.JButton();
        jTextFieldNome = new com.estoque.telas.icons.JTextFieldHint(new JTextField(), "empty", "Nome do produto");
        ;
        jTextFieldPreco = new com.estoque.telas.icons.JTextFieldHint(new JTextField(), "empty", "Preço");
        ;
        jTextFieldQuantidade = new com.estoque.telas.icons.JTextFieldHint(new JTextField(), "empty", "Quantidade");
        ;
        jTextFieldDescricao = new com.estoque.telas.icons.JTextFieldHint(new JTextField(), "empty", "Descrição");
        ;
        jComboBoxTipoQuantidade = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCodigoNovo = new javax.swing.JTextField();

        jButtonPesquisar.setBackground(new java.awt.Color(58, 65, 84));
        jButtonPesquisar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPesquisar.setText("Remover");
        jButtonPesquisar.setBorder(null);
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 400));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EDITAR PRODUTO");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\julio\\Downloads\\packages.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27))))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 90));

        jButtonRetornarMenuProduto.setBackground(new java.awt.Color(217, 81, 51));
        jButtonRetornarMenuProduto.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButtonRetornarMenuProduto.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRetornarMenuProduto.setText("Retornar");
        jButtonRetornarMenuProduto.setToolTipText("");
        jButtonRetornarMenuProduto.setBorder(null);
        jButtonRetornarMenuProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRetornarMenuProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonRetornarMenuProdutoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonRetornarMenuProdutoMouseExited(evt);
            }
        });
        jButtonRetornarMenuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetornarMenuProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRetornarMenuProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 250, 40));

        jLabel3.setBackground(new java.awt.Color(204, 0, 0));
        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Atualize as informações do produto:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 600, 40));

        jButtonSalvar.setBackground(new java.awt.Color(58, 65, 84));
        jButtonSalvar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButtonSalvar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setBorder(null);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 250, 40));

        jTextFieldCodigo.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextFieldCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 200, 25));

        jButtonEditar.setBackground(new java.awt.Color(58, 65, 84));
        jButtonEditar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonEditar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditar.setText("Editar");
        jButtonEditar.setBorder(null);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 120, 30));

        jTextFieldNome.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 200, 25));

        jTextFieldPreco.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextFieldPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 200, 25));

        jTextFieldQuantidade.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextFieldQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 200, 25));

        jTextFieldDescricao.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextFieldDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 240, 40));

        jComboBoxTipoQuantidade.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxTipoQuantidade.setEditable(true);
        jComboBoxTipoQuantidade.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jComboBoxTipoQuantidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KG", "Unidade" }));
        jComboBoxTipoQuantidade.setToolTipText("");
        jPanel1.add(jComboBoxTipoQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 200, 25));

        jLabel4.setBackground(new java.awt.Color(204, 0, 0));
        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Informe o código do produto:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 600, 40));

        jTextFieldCodigoNovo.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextFieldCodigoNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 200, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        //r TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // try-catch para confirmar se o produto existe ou não
        try {
            // atribui o valor dos parâmetros abaixo de acordo com o conteúdo recuperado em cada uma
            // das caixas de texto e do combobox
            int codigo = Integer.parseInt(jTextFieldCodigoNovo.getText());
            String novoNome = jTextFieldNome.getText();
            String novoTipoQuantidade = (String) jComboBoxTipoQuantidade.getSelectedItem();
            String novaDescricao = jTextFieldDescricao.getText();
            double novoPreco = Double.parseDouble(jTextFieldPreco.getText());
            double novaQuantidade = Double.parseDouble(jTextFieldQuantidade.getText());
            
            // se o novoPreco for um valor válido, entra no if
            if (novoPreco <= 0 || novoPreco >= 100000) {
                // try-catch para confirmar que o valor inserido é válido
                try {
                    // chama o método updatePreco da lista de produtos para atualizar o preço
                    produtos.updatePreco(codigo, novoPreco);
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Insira um preço válido!");
                    // se o programa lançar a exceção, limpa o campo e retorna
                    jTextFieldPreco.setText("");
                    return;
                }
            }

            // se o valor inserido for válido de acordo com a regra, entra no if
            if(novaQuantidade <= 0 || novaQuantidade >= 100000) {
                // try-catch para confirmar que o numero inserido é válido
                try {
                    // chama o método addQuantidade para adicionar o número inserido a quantidade existente
                    produtos.addQuantidade(codigo, novaQuantidade);
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Insira uma quantidade válida");
                    // se o programa lançar a exceção, limpa o campo e retorna
                    jTextFieldQuantidade.setText("");
                    return;
                }
            }

            // atribui os novos valores, caso tenham sido modificados, para o produto usando os setters
            produtos.getProduto(codigo).setNome(novoNome);
            produtos.getProduto(codigo).setPreco(novoPreco);
            produtos.getProduto(codigo).setDescricao(novaDescricao);
            produtos.getProduto(codigo).setTipoQuantidade(novoTipoQuantidade);
            // grava a lista de produtos com o produto editado
            gravarLista(produtos);
            JOptionPane.showMessageDialog(null, "Produto editado!");
        } catch (ProdutoNaoEncontradoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonRetornarMenuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetornarMenuProdutoActionPerformed
        new MenuProdutos(this.produtos).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonRetornarMenuProdutoActionPerformed

    private void jButtonRetornarMenuProdutoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRetornarMenuProdutoMouseExited
        jButtonRetornarMenuProduto.setBackground(new Color(217,81,51));
        jButtonRetornarMenuProduto.setForeground(new Color(235,235,235));
    }//GEN-LAST:event_jButtonRetornarMenuProdutoMouseExited

    private void jButtonRetornarMenuProdutoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRetornarMenuProdutoMouseEntered
        jButtonRetornarMenuProduto.setBackground(new Color(235,235,235));
        jButtonRetornarMenuProduto.setForeground(new Color(217,81,51));
    }//GEN-LAST:event_jButtonRetornarMenuProdutoMouseEntered

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
       
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // atualiza a visibilidade de vários itens da tela
        jButtonEditar.setVisible(false);
        jTextFieldCodigo.setVisible(false);
        jLabel4.setVisible(false);
        jTextFieldNome.setVisible(true);
        jTextFieldPreco.setVisible(true);
        jTextFieldQuantidade.setVisible(true);
        jComboBoxTipoQuantidade.setVisible(true);
        jTextFieldDescricao.setVisible(true);
        jLabel3.setVisible(true);

        int codigo;
        // determina que o valor de código é o valor informado no campo jTextFieldCodigo
        codigo = Integer.parseInt(jTextFieldCodigo.getText());

        // se o código não for igual a 0, entra no if
        if(codigo != 0) {
            // try-catch para confirmar se o produto com o código informado existe
            try {
                // recupera o produto e seta os parâmetros a seguir com os valores do produto
                codigo = produtos.getProduto(codigo).getCodigo();
                String nome = produtos.getProduto(codigo).getNome();
                String tipoQuantidade = produtos.getProduto(codigo).getTipoQuantidade();
                String descricao = produtos.getProduto(codigo).getDescricao();
                double preco = produtos.getProduto(codigo).getPreco();
                double quantidade =produtos.getProduto(codigo).getQuantidade();

                // atribui os valores recuperados do produto em questão nos campos da tela para que sejam
                // editados de acordo com a intenção do usuário
                jTextFieldCodigoNovo.setText(Integer.toString(codigo));
                jTextFieldNome.setText(nome);
                jTextFieldPreco.setText(Double.toString(preco));
                jTextFieldQuantidade.setText(Double.toString(quantidade));
                // if para recuperar o tipo de quantidade selecionado no ComboBox
                if(tipoQuantidade == "KG") {
                    jComboBoxTipoQuantidade.setSelectedItem("Unidade");   
                } else {
                    jComboBoxTipoQuantidade.setSelectedItem("KG");
                }
                jTextFieldDescricao.setText(descricao);
            } catch (ProdutoNaoEncontradoException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());

                // atualiza a visibilidade dos itens do painel novamente
                jButtonEditar.setVisible(true);
                jTextFieldCodigo.setVisible(true);
                jTextFieldCodigo.setText("");
                jLabel4.setVisible(true);
                jTextFieldNome.setVisible(false);
                jTextFieldPreco.setVisible(false);
                jTextFieldQuantidade.setVisible(false);
                jComboBoxTipoQuantidade.setVisible(false);
                jTextFieldDescricao.setVisible(false);
                jLabel3.setVisible(false);
            }
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EditarProduto().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonRetornarMenuProduto;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxTipoQuantidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldCodigoNovo;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPreco;
    private javax.swing.JTextField jTextFieldQuantidade;
    // End of variables declaration//GEN-END:variables
}
